# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# Defafult pipepline template is located at https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

image: node:latest

cache:
  paths:
    - node_modules/

stages: # List of stages for jobs, and their order of execution
  - test

lint-test-job:
  image: node:latest
  stage: test
  script:
    - echo "Preparing the environment..."
    - npm install
    - echo "Linting code with Prettier..."
    - npm run prettier:check:ci
